apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: developer
rules: # each rule has 3 sections
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "create", "list", "delete"]
- apiGroups: [""]
  resources: ["ConfigMap"]
  verbs: ["create"]
